### ISSUE TITLE
What about removing lodash from dependency?

### ISSUE THREAD

**Issue by Snack-X** [bemusic/bms-js#20]
Of course, I know that lodash is very strong and useful, but big utility library.

While making some _thing_(https://github.com/Snack-X/web-bms-viewer), I browserify-ed bms-js. And it became a huge `.js` file. I separated lodash from dependency to external `.js` file, and it became smaller (my build is about 22K). But lodash is still 50K(minified and modern build from https://lodash.com/).

I don't know which is good way. You may leave lodash and use at other part, or remove lodash and re-implement those lodash parts.

---

I tried to reimplement lodash thing (I found `_.uniq`, `_.values`, `_.pluck`). You can see it [here](https://github.com/Snack-X/web-bms-viewer/blob/master/dep/bmsjs/util/utils.js). It was my implementation, and might be slower than lodash. If you chose to reimplement lodash things, you may use this implementation, or by yourself.

(I know my browserfy-ing ways are weird.)

**Comment by dtinth** [comment]
Hello. Thanks for writing in!

On npm there are separate lodash module for each function too.

For example, this one:

https://www.npmjs.com/package/lodash.uniq

I think I can try replacing the lodash require with these modules.

**Comment by dtinth** [comment]
Hi again. Sorry, my email client has a problem and discards everything after the 2nd sentence. :cry: 

v0.12.0 is (going to be) released with the following changes:
- It now depends on a modularized version of lodash — namely, [lodash.pluck](https://www.npmjs.com/packages/lodash.pluck), [lodash.uniq](https://www.npmjs.com/packages/lodash.uniq), [lodash.values](https://www.npmjs.com/packages/lodash.values).
- It instructed Browserify to use the web version of BMS.Reader (which uses `FileReader`) instead of Node.js version (which relies on `iconv-lite`).

With this, the size of bms-js becomes smaller:
- Simple browserify:
  
  ```
  ▹ browserify index.js | wc -c
  200743
  ```
- Uglified:
  
  ```
  ▹ browserify index.js | uglifyjs | wc -c
  95171
  ```
- Uglified and gzipped:
  
  ```
  ▹ browserify index.js | uglifyjs | gzip | wc -c
  23716
  ```

Therefore, bms.js size has now reduced to 23 kb when minified and gzipped.

**Comment by dtinth** [comment]
Closing this, as 0.12.0 is now live.
